config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "cookings#index"
  resources :cookings, only: [:index, :new, :create, :show, :destroy, :edit, :update]
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: 'お肉のおかず' },
    { id: 2, name: '魚介のおかず' },
    { id: 3, name: '野菜のおかず' },
    { id: 4, name: 'パスタ・グラタン' },
    { id: 5, name: 'ごはんもの' },
    { id: 6, name: 'サラダ' },
    { id: 7, name: '麺' },
    { id: 8, name: 'シチュー・スープ・汁物' },
    { id: 9, name: '鍋' }
  ]

  include ActiveHash::Associations
  has_many :cookings
end

app/models/cooking.rb
class Cooking < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :user
  has_one :ingredient
  has_one_attached :image
end

app/models/cooking_ingredient.rb
class CookingIngredient
  include ActiveModel::Model
  attr_accessor :image, :name, :category_id, :ingredient1, :ingredient2, :ingredient3, :ingredient4, :ingredient5, :ingredient6,
                :ingredient7, :user_id,
                :id, :cooking_id, :created_at, :datetime, :updated_at, :datetime

  with_options presence: true do
    validates :image
    validates :name
    validates :category_id
    validates :user_id
  end

  def save
    cooking = Cooking.create(image: image, name: name, category_id: category_id, user_id: user_id)
    ingredient = Ingredient.create(ingredient1: ingredient1, ingredient2: ingredient2, ingredient3: ingredient3, ingredient4: ingredient4,
                      ingredient5: ingredient5, ingredient6: ingredient6, ingredient7: ingredient7, cooking_id: cooking.id)
  end

  def update(id)
    cooking = Cooking.find(id)
    ingredient = cooking.ingredient
    cooking.update(image: image, name: name, category_id: category_id, user_id: user_id)
    ingredient.update(ingredient1: ingredient1, ingredient2: ingredient2, ingredient3: ingredient3, ingredient4: ingredient4,
                      ingredient5: ingredient5, ingredient6: ingredient6, ingredient7: ingredient7, cooking_id: cooking.id)
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :cooking
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cookings

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cookings_controller.rb
class CookingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :destroy]
  def index
    if user_signed_in?
      cookings = Cooking.where(user_id: current_user.id)
      @random = cookings.order('RAND()').limit(5)
      @cookings = cookings.all
    end
  end

  def new
    @cooking_ingredient = CookingIngredient.new
  end

  def create
    @cooking_ingredient = CookingIngredient.new(cooking_params)
    if @cooking_ingredient.valid?
      @cooking_ingredient.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @cooking = Cooking.find(params[:id])
    @ingredient = @cooking.ingredient
  end

  def destroy
    @cooking = Cooking.find(params[:id])
    if current_user.id == @cooking.user_id
      @cooking.ingredient.destroy
      @cooking.destroy
    end
    redirect_to user_path(current_user.id)
  end

  def edit
    @cooking = Cooking.find(params[:id])
    @ingredient = @cooking.ingredient
    cooking_attributes = @cooking.attributes
    ingredient_attributes = @ingredient.attributes
    cooking_ingredient = cooking_attributes.merge(ingredient_attributes)
    @cooking_ingredient = CookingIngredient.new(cooking_ingredient)
  end

  def update
    @cooking = Cooking.find(params[:id])
    @cooking_ingredient = CookingIngredient.new(cooking_params)
    @cooking_ingredient.image ||= @cooking.image.blob
    if @cooking_ingredient.valid?
      @cooking_ingredient.update(@cooking.id)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  private 

  def cooking_params
    params.require(:cooking_ingredient).permit(:image, :name, :category_id, :ingredient1, :ingredient2, :ingredient3,
                                               :ingredient4, :ingredient5, :ingredient6, :ingredient7).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show
  def show
    @name = current_user.name
    @cookings = current_user.cookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookings_helper.rb
module CookingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cookings/edit.html.erb
<div class="cookings-sell-contents">
  <div class="cookings-sell-main">
    <h2 class="cookings-sell-title">料理情報を編集</h2>
    <%= form_with model: @cooking_ingredient, url: cooking_path(@cooking.id), method: :patch, local: true do |f| %>

    <%# 料理画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        料理画像
      </div>
      <div class="click-upload">
        <p>
          クリックして写真をアップロード  
        </p>
        <%= f.file_field :image, id:"cooking-image" %>
      </div>
    </div>
    <%# /料理画像 %>
    <%# 料理情報入力 %> 
    <div class="new-cookings">
      <div class="weight-bold-text">
        料理名
      </div>
      <%= f.text_area :name, class:"cookings-text", id:"cooking-name", placeholder:"料理名を入力" %>
      <div class="cookings-category">
        <div class="weight-bold-text">
          カテゴリー
        </div>
        <%= f.collection_select :category_id, Category.all, :id, :name, {}, {class:"category-select"} %>
      </div>
      <div class="weight-bold-text">
        材料(任意)
      </div>
      <%= f.text_area :ingredient1, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient2, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient3, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient4, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient5, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient6, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient7, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
    </div>
    <%# /料理情報入力 %>



    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "料理を編集する" ,class:"sell-btn btn btn-success" %>
      <%=link_to 'もどる', root_path, class:"back-btn btn btn-secondary" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/cookings/index.html.erb
<div class='item-contents'>
  <a class="btn btn-warning" href="">ランダム</a>
  <div class="subtitle" >
    献立リスト
  </div>
  <ul class='item-lists'>
    <% if user_signed_in? && @cookings.length != 0 %>
      <% @random.each do |cooking| %>
        <li class='list'>
          <%= link_to cooking_path(cooking.id) do %>
          <div class='item-img-content'>
            <%= image_tag cooking.image, class: 'item-img' %>
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= cooking.name %>
            </h3>
            <div class='item-price'>
              <span><%= cooking.category.name %></span>
            </div>
          </div>
          <div class="ingredients-dropdown">
            <button class="btn btn-secondary btn-sm dropdown-toggle btn-success" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              材料リスト
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li><%= cooking.ingredient.ingredient1 %></li>
              <li><%= cooking.ingredient.ingredient2 %></li>
              <li><%= cooking.ingredient.ingredient3 %></li>
              <li><%= cooking.ingredient.ingredient4 %></li>
              <li><%= cooking.ingredient.ingredient5 %></li>
              <li><%= cooking.ingredient.ingredient6 %></li>
              <li><%= cooking.ingredient.ingredient7 %></li>
            </ul>
          </div>          
          <% end %>
        </li>
      <% end %>
    <% else %>
      <li class='list'>
        <%= link_to '#' do %>
          <%= image_tag("6422cf540f1af648323d959c54dffb7659cb38c3.82.2.3.2.jpg", class: "item-img") %>
          <div class='item-info'>
            <h3 class='item-name'>
              料理を登録してね！
            </h3>
          </div>
        <% end %>
      </li>
    <% end %>

   
  </ul>
</div>

app/views/cookings/new.html.erb
<div class="cookings-sell-contents">
  <div class="cookings-sell-main">
    <h2 class="cookings-sell-title">料理情報を入力</h2>
    <%= form_with model: @cooking_ingredient, url: cookings_path, local: true do |f| %>

    <%# 料理画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        料理画像
      </div>
      <div class="click-upload">
        <p>
          クリックして写真をアップロード
        </p>
        <%= f.file_field :image, id:"cooking-image" %>
      </div>
    </div>
    <%# /料理画像 %>
    <%# 料理情報入力 %>
    <div class="new-cookings">
      <div class="weight-bold-text">
        料理名
      </div>
      <%= f.text_area :name, class:"cookings-text", id:"cooking-name", placeholder:"料理名を入力" %>
      <div class="cookings-category">
        <div class="weight-bold-text">
          カテゴリー
        </div>
        <%= f.collection_select :category_id, Category.all, :id, :name, {}, {class:"category-select"} %>
      </div>
      <div class="weight-bold-text">
        材料(任意)
      </div>
      <%= f.text_area :ingredient1, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient2, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient3, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient4, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient5, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient6, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
      <div class="weight-bold-text">
      </div>
      <%= f.text_area :ingredient7, class:"cookings-text", id:"cooking-name", placeholder:"材料名を入力" %>
    </div>
    <%# /料理情報入力 %>



    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "料理登録する" ,class:"sell-btn btn btn-success" %>
      <%=link_to 'もどる', root_path, class:"back-btn btn btn-secondary" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/cookings/show.html.erb
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @cooking.name %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @cooking.image ,class:"item-box-img img-thumbnail" %>
    </div>
    <div class="item-price-box">
      <span class="item-postate">
        <%= @cooking.category.name %>
      </span>
    </div>
    <div class="ingredients">
      <h4>材料リスト</h4>
      <ul class="ingredients-list">
        <% unless @ingredient.ingredient1 == "" %>
          <li><%= @ingredient.ingredient1 %></li>
        <% end %>
        <% unless @ingredient.ingredient2 == "" %>
          <li><%= @ingredient.ingredient2 %></li>
        <% end %>
        <% unless @ingredient.ingredient3 == "" %>
          <li><%= @ingredient.ingredient3 %></li>
        <% end %>
        <% unless @ingredient.ingredient4 == "" %>
          <li><%= @ingredient.ingredient4 %></li>
        <% end %>
        <% unless @ingredient.ingredient5 == "" %>
          <li><%= @ingredient.ingredient5 %></li>
        <% end %>
        <% unless @ingredient.ingredient6 == "" %>
          <li><%= @ingredient.ingredient6 %></li>
        <% end %>
        <% unless @ingredient.ingredient7 == "" %>
          <li><%= @ingredient.ingredient7 %></li>
        <% end %>
      </ul>
    </div>
    <% if user_signed_in? && @cooking.user_id == current_user.id %>
      <div class="d-inline-block mt-5">
        <%= link_to "料理の編集", edit_cooking_path(@cooking.id), method: :get, class: "btn btn-secondary btn-lg" %>
        <%= link_to "削除", cooking_path(@cooking.id), method: :delete, class:"btn btn-danger btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   

    <title>kondate</title>
  </head>
  <body>
    <header class="nav-header">
      <div class="navbar-inner">
        <div class="navbar bg-light mt-3 mb-3">
          <div class="nav-left">
            <a class="navbar-brand mb-0 h1 fs-1 fw-bold" href="/">献立ランダムアプリ</a>
          </div>
          <% if user_signed_in? %>
            <div class="pull-right">
              <div class="dropdown d-inline-block">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_user.name %>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li><%= link_to "マイページ", "/users/#{current_user.id}", class:"dropdown-item" %></li>
                  <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
                </ul>
              </div>
              <div class = "get-cooking d-inline-block">
                <a class="btn btn-primary" href="/cookings/new" role="button">料理登録
                </a>
              </div>
            </div>
          <% else %>
          <div class="pull-right">
            <a class="btn btn-primary" href="/users/sign_in" role="button">ログイン
            </a>
            <a class="btn btn-primary" href="/users/sign_up" role="button">新規登録
            </a>
          </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>    
    <!-- ここにメインの処理を書く -->
 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/show.html.erb
<div class="item-contents">
  <div class="subtitle">
    <%= "#{@name}さんの料理一覧" %>
  </div>
  <ul class="item-lists">
    <% @cookings.each do |cooking| %>
      <li class='list'>
        <%= link_to cooking_path(cooking.id) do %>
          <div class='item-img-content'>
            <%= image_tag cooking.image, class: 'item-img' %>
          </div>
          <div class='item-info'>
            <h3 class='item-name'>
              <%= cooking.name %>
            </h3>
            <div class='item-price'>
              <span><%= cooking.category.name %></span>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>